default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
        ssl: true
        address: "smtp.exmail.qq.com"
        port: 465
        domain: "cc.com"
        authentication: :plain
        user_name: "yy@cc.com"
        password: "xx"
  attachments_storage_path: '/redmine/files'
  autologin_cookie_name: 'al_uszch'
  autologin_cookie_secure: true
production:
development:
